### ISSUE TITLE
caffe_.mexw64: Invalid MEX-file

### ISSUE THREAD

**Issue by yzhsjtu** [ShaoqingRen/faster_rcnn#7] opened 2015-09-14 20:00 UTC
Invalid MEX-file '...\faster_rcnn-master\external\caffe\matlab\caffe_faster_rcnn\caffe_.mexw64': The specified procedure could not be found.

Error in caffe.get_net (line 27)
hNet = caffe_('get_net', model_file, phase_name);

Error in caffe.Net (line 33)
        self = caffe.get_net(varargin{:});

Error in script_faster_rcnn_demo (line 33)
rpn_net = caffe.Net(proposal_detection_model.proposal_net_def, 'test');

**Comment by yzhsjtu** [comment] 2015-09-14 22:14
The caffe_.mexw64 was downloaded from dropbox link.

**Comment by ShaoqingRen** [comment] 2015-09-15 02:58
Please check whether system environments are compatible with the downloaded mex (including cuda 6.5, vs2013, windows 7/8).

**Comment by AlexGruzdev** [comment] 2015-09-16 13:06
Almost the same thing for me too (but for Ubuntu OS):

Mex file entry point is missing.  Please check the (case-sensitive) 
spelling of mexFunction (for C MEX-files), or the (case-insensitive) 
spelling of MEXFUNCTION (for FORTRAN MEX-files).
Invalid MEX-file '/home/agruzdev/git/faster_rcnn/external/caffe/matlab/+caffe/private/caffe_.mexa64':

Error in caffe.get_net (line 27)
hNet = caffe_('get_net', model_file, phase_name);

Error in caffe.Net (line 33)
        self = caffe.get_net(varargin{:});

Error in script_faster_rcnn_demo (line 33)
rpn_net = caffe.Net(proposal_detection_model.proposal_net_def, 'test');

The caffe_.mexa64 was build from the latest version of caffe for faster r-cnn.

**Comment by ShaoqingRen** [comment] 2015-09-16 13:42
@AlexGruzdev For Ubuntu, the compliing phase is the same as official Caffe.

**Comment by AlexGruzdev** [comment] 2015-09-16 13:55
@ShaoqingRen I didn't download caffe_.mexa64 file, I did compilation according official Caffe instructions.

**Comment by smichalowski** [comment] 2015-09-17 21:56
@ShaoqingRen I have same problem as @AlexGruzdev...

configured using cmake, after trying to load caffe_:
using debian jessie, matlab R2014a:

> caffe_
Mex file entry point is missing.  Please check the (case-sensitive)
spelling of mexFunction (for C MEX-files), or the (case-insensitive)
spelling of MEXFUNCTION (for FORTRAN MEX-files).
Invalid MEX-file '/home/smichalowski/faster_rcnn/external/caffe/matlab/+caffe/private/caffe_.mexa64':

**Comment by rbgirshick** [comment] 2015-09-18 16:12
I haven't been able to reproduce this problem on Linux. I'm using matlab R2014a, gcc 4.8.4, ubuntu 14.04.3.

@AlexGruzdev, @smichalowski When you cloned the faster_rcnn repo, did you use `git clone --recursive`? If not, please try that to make sure that you're on the correct commit for the caffe submodule (d1d96fe).

**Comment by smichalowski** [comment] 2015-09-18 16:16
hi @rbgirshick 

Yes, I cloned faster_rcnn with --recursive option.
Today Ive tried ubuntu 15.04 + gcc 4.7 + matlab R2014a - same error.
caffe was built using cmake, I'll try again with standard make and Makefile.config

**Comment by rbgirshick** [comment] 2015-09-18 16:21
The issue could be with cmake. I used make and [this Makefile.config](http://www.cs.berkeley.edu/~rbg/fast-rcnn-data/Makefile.config).

**Comment by rbgirshick** [comment] 2015-09-18 16:51
The issue is most likely that the cmake build is not defining `BUILD_MEX_INTERFACE`. `Makefile` was modified to add `-DBUILD_MEX_INTERFACE` to the `CXXFLAGS`.

@ShaoqingRen, was there a reason for adding the `BUILD_MEX_INTERFACE` guard? Perhaps it should just be removed from caffe_.cpp.

**Comment by ShaoqingRen** [comment] 2015-09-18 16:55
@rbgirshick BUILD_MEX_INTERFACE is used in VS solution, I'll make BUILD_MEX_INTERFACE only affect in Windows.

**Comment by ShaoqingRen** [comment] 2015-09-18 17:18
@AlexGruzdev @smichalowski The BUILD_MEX_INTERFACE only functions on Windows now. Please have a try with the new version.

**Comment by smichalowski** [comment] 2015-09-19 23:24
yes, compiled without errors. thank you

**Comment by AlexGruzdev** [comment] 2015-09-21 10:39
With your last version of caffe I got the following:

Building with 'g++'.
/home/agruzdev/git/faster_rcnn/external/caffe/matlab/+caffe/private/caffe_.cpp:19:28: fatal error: gpu/mxGPUArray.h: No such file or directory
compilation terminated.

make[2]: *** [matlab/+caffe/private/caffe_.mexa64] Error 255
make[1]: *** [matlab/CMakeFiles/matlab.dir/all] Error 2
make: *** [all] Error 2

**Comment by rbgirshick** [comment] 2015-09-21 15:14
@AlexGruzdev - please use the Makefile build; the cmake build is unsupported in this fork. We updated the Makefile to add the following include path and lib for compiling the matlab wrapper:
`MATLAB_INCLUDE := -I$(MATLAB_DIR)/toolbox/distcomp/gpu/extern/include`
`MATLAB_LIBS := -lmwgpu`
If you wish to use cmake, you'll need to incorporate these additions into the cmake build.

**Comment by AlexGruzdev** [comment] 2015-09-21 19:28
@ShaoqingRen @rbgirshick Thank you, guys!
Compilation without errors.

**Comment by rbgirshick** [comment] 2015-09-21 19:36
Great. Closing this issue.

**Closed by rbgirshick** 2015-09-21 19:36 UTC

**Comment by empty16** [comment] 2016-04-06 15:39
thanks for you guys

**Comment by TX2012LH** [comment] 2016-05-21 04:30
I just met the same problem, but it does no effect after I add them as above. I git clone the version caffe of faster rcnn and build it in ubuntu14.04.

**Comment by haoyul** [comment] 2016-08-07 22:23
@rbgirshick I didn't find this distcomp toolbox under my R2014a student matlab. Is it not available in student version?

**Comment by jacobunderlinebenseal** [comment] 2016-12-15 03:15
there is a cuda7.5 version in the rfcn github, i download it and set tu cpu mode and it works...

**Comment by mustansarfiaz** [comment] 2017-03-27 05:59
Please guide.
My [problem link](http://stackoverflow.com/questions/43038644/makefile517-recipe-for-target-matlab-caffe-private-caffe-mexa64-failed-mak)

**Comment by mustansarfiaz** [comment] 2017-03-27 06:00
Please guide me.

My detailed[ problem link](http://stackoverflow.com/questions/43038644/makefile517-recipe-for-target-matlab-caffe-private-caffe-mexa64-failed-mak) is here.

**Comment by derekwong66** [comment] 2017-04-10 21:12
how to acquire caffe_.mexa64 under LINUX?
